package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final

/**
 * Adminusers generated by hbm2java
 */
public class Adminusers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1266853866627060981L;
	private String adminUserId;
	private String username;
	private String password;
	private String email;
	private boolean isActive;

	public Adminusers() {
	}

	public Adminusers(String adminUserId, String username, String password, String email, boolean isActive) {
		this.adminUserId = adminUserId;
		this.username = username;
		this.password = password;
		this.email = email;
		this.isActive = isActive;
	}

	public String getAdminUserId() {
		return this.adminUserId;
	}

	public void setAdminUserId(String adminUserId) {
		this.adminUserId = adminUserId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
