package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4562619035144480536L;
	private String companyId;
	private Country country;
	private String name;
	private String username;
	private String password;
	private String accessToken;
	@JsonIgnore
	private String lastAccessTime;
	@JsonIgnore
	private Set<Device> devices = new HashSet<Device>(0);
	@JsonIgnore
	private Set<Subscriber> subscribers = new HashSet<Subscriber>(0);
	@JsonIgnore
	private Set<Sessionlist> sessions = new HashSet<Sessionlist>(0);

	public Company() {
	}

	public Company(String companyId, Country country, String name, String username, String password, String accessToken, String lastAccessTime) {
		this.companyId = companyId;
		this.country = country;
		this.name = name;
		this.username = username;
		this.password = password;
		this.accessToken = accessToken;
		this.lastAccessTime = lastAccessTime;
	}

	public Company(String companyId, Country country, String name, String username, String password, String accessToken, String lastAccessTime, Set<Device> devices, Set<Subscriber> subscribers, Set<Sessionlist> sessions) {
		this.companyId = companyId;
		this.country = country;
		this.name = name;
		this.username = username;
		this.password = password;
		this.accessToken = accessToken;
		this.lastAccessTime = lastAccessTime;
		this.devices = devices;
		this.subscribers = subscribers;
		this.sessions = sessions;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	
	public Country getCountry() {
		return this.country;
	}


	public void setCountry(Country country) {
		this.country = country;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}

	public Set<Subscriber> getSubscribers() {
		return this.subscribers;
	}

	public void setSubscribers(Set<Subscriber> subscribers) {
		this.subscribers = subscribers;
	}
	
	public Set<Sessionlist> getSessions() {
		return this.sessions;
	}

	public void setSessions(Set<Sessionlist> sessions) {
		this.sessions = sessions;
	}

	public String getAccessToken() {
		return accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public String getLastAccessTime() {
		return lastAccessTime;
	}

	public void setLastAccessTime(String lastAccessTime) {
		this.lastAccessTime = lastAccessTime;
	}

}
