package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8411349000077416423L;
	private String countryId;
	private String countryName;
	@JsonIgnore
	private Set<Productcoverage> productcoverages = new HashSet<Productcoverage>(0);
	@JsonIgnore
	private Set<Usage> usages = new HashSet<Usage>(0);
	@JsonIgnore
	private Set<Company> companies = new HashSet<Company>(0);

	public Country() {
	}

	public Country(String countryId, String countryName) {
		this.countryId = countryId;
		this.countryName = countryName;
	}

	public Country(String countryId, String countryName, Set<Productcoverage> productcoverages, Set<Usage> usages,
			Set<Company> companies) {
		this.countryId = countryId;
		this.countryName = countryName;
		this.productcoverages = productcoverages;
		this.usages = usages;
		this.companies = companies;
	}

	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public Set<Productcoverage> getProductcoverages() {
		return this.productcoverages;
	}

	public void setProductcoverages(Set<Productcoverage> productcoverages) {
		this.productcoverages = productcoverages;
	}

	public Set<Usage> getUsages() {
		return this.usages;
	}

	public void setUsages(Set<Usage> usages) {
		this.usages = usages;
	}

	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
