package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1377991269296165431L;
	private String deviceId;
	private Company company;
	private Product product;
	private String imei;
	private String msisdn;
	private String zteref;
	private String ref;
	private String comment;
	private String support;
	private boolean isActive;
	private String invoiceName;
	private String invoiceNumber;
	private String period;
	private String rinvNo;
	private int bundlesUsed;
	private String sim;
	@JsonIgnore
	private Set<Subscriber> subscribers = new HashSet<Subscriber>(0);
	@JsonIgnore
	private Set<Apploginhistory> apploginhistories = new HashSet<Apploginhistory>(0);
	@JsonIgnore
	private Set<Usage> usages = new HashSet<Usage>(0);

	public Device() {
	}

	public Device(String deviceId, Product product, String imei, String msisdn, String zteref, String ref, boolean isActive, String invoiceName, String invoiceNumber, String period, String rinvNo, int bundlesUsed, String sim) {
		this.deviceId = deviceId;
		this.product = product;
		this.imei = imei;
		this.msisdn = msisdn;
		this.zteref = zteref;
		this.ref = ref;
		this.isActive = isActive;
		this.invoiceName = invoiceName;
		this.invoiceNumber = invoiceNumber;
		this.period = period;
		this.rinvNo = rinvNo;
		this.bundlesUsed = bundlesUsed;
		this.sim = sim;
	}

	public Device(String deviceId, Company company, Product product, String imei, String msisdn, String zteref,
			String ref, String comment, String support, boolean isActive, String invoiceName, String invoiceNumber, String period, String rinvNo, int bundlesUsed, String sim, Set<Subscriber> subscribers,
			Set<Apploginhistory> apploginhistories, Set<Usage> usages) {
		this.deviceId = deviceId;
		this.company = company;
		this.product = product;
		this.imei = imei;
		this.msisdn = msisdn;
		this.zteref = zteref;
		this.ref = ref;
		this.comment = comment;
		this.support = support;
		this.isActive = isActive;
		this.invoiceName = invoiceName;
		this.invoiceNumber = invoiceNumber;
		this.period = period;
		this.rinvNo = rinvNo;
		this.bundlesUsed = bundlesUsed;
		this.subscribers = subscribers;
		this.apploginhistories = apploginhistories;
		this.sim = sim;
		this.usages = usages;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}


	public Company getCompany() {
		return this.company;
	}

	
	public void setCompany(Company company) {
		this.company = company;
	}

	public Product getProduct() {
		return this.product;
	}
	public void setProduct(Product product) {
		this.product = product;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getZteref() {
		return this.zteref;
	}

	public void setZteref(String zteref) {
		this.zteref = zteref;
	}
	
	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getSupport() {
		return this.support;
	}

	public void setSupport(String support) {
		this.support = support;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}
	
	public String getInvoiceName() {
		return invoiceName;
	}

	public void setInvoiceName(String invoiceName) {
		this.invoiceName = invoiceName;
	}

	public String getInvoiceNumber() {
		return invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public String getPeriod() {
		return period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getRinvNo() {
		return rinvNo;
	}

	public void setRinvNo(String rinvNo) {
		this.rinvNo = rinvNo;
	}

	public int getBundlesUsed() {
		return this.bundlesUsed;
	}

	public void setBundlesUsed(int bundlesUsed) {
		this.bundlesUsed = bundlesUsed;
	}
	
	public Set<Subscriber> getSubscribers() {
		return this.subscribers;
	}

	public void setSubscribers(Set<Subscriber> subscribers) {
		this.subscribers = subscribers;
	}

	public Set<Apploginhistory> getApploginhistories() {
		return this.apploginhistories;
	}

	public void setApploginhistories(Set<Apploginhistory> apploginhistories) {
		this.apploginhistories = apploginhistories;
	}

	public String getSim() {
		return this.sim;
	}

	public void setSim(String sim) {
		this.sim = sim;
	}

	public Set<Usage> getUsages() {
		return this.usages;
	}

	public void setUsages(Set<Usage> usages) {
		this.usages = usages;
	}

}
