package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final

/**
 * Productcoverage generated by hbm2java
 */
public class Productcoverage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 747338318472475881L;
	private String productCoverageId;
	private Country country;
	private Product product;

	public Productcoverage() {
	}

	public Productcoverage(String productCoverageId, Country country, Product product) {
		this.productCoverageId = productCoverageId;
		this.country = country;
		this.product = product;
	}

	public String getProductCoverageId() {
		return this.productCoverageId;
	}

	public void setProductCoverageId(String productCoverageId) {
		this.productCoverageId = productCoverageId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
