package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Productsupport generated by hbm2java
 */
public class Productsupport implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2864059075484466876L;
	private String productSupportId;
	private Product product;
	private String heading1;
	private String headingText1;
	private String heading2;
	private String headingText2;

	public Productsupport() {
	}

	public Productsupport(String productSupportId, String heading1, String headingText1) {
		this.productSupportId = productSupportId;
		this.heading1 = heading1;
		this.headingText1 = headingText1;
	}

	public Productsupport(String productSupportId, Product product, String heading1, String headingText1,
			String heading2, String headingText2) {
		this.productSupportId = productSupportId;
		this.product = product;
		this.heading1 = heading1;
		this.headingText1 = headingText1;
		this.heading2 = heading2;
		this.headingText2 = headingText2;
	}

	public String getProductSupportId() {
		return this.productSupportId;
	}

	public void setProductSupportId(String productSupportId) {
		this.productSupportId = productSupportId;
	}

	@JsonIgnore
	public Product getProduct() {
		return this.product;
	}

	@JsonProperty
	public void setProduct(Product product) {
		this.product = product;
	}

	public String getHeading1() {
		return this.heading1;
	}

	public void setHeading1(String heading1) {
		this.heading1 = heading1;
	}

	public String getHeadingText1() {
		return this.headingText1;
	}

	public void setHeadingText1(String headingText1) {
		this.headingText1 = headingText1;
	}

	public String getHeading2() {
		return this.heading2;
	}

	public void setHeading2(String heading2) {
		this.heading2 = heading2;
	}

	public String getHeadingText2() {
		return this.headingText2;
	}

	public void setHeadingText2(String headingText2) {
		this.headingText2 = headingText2;
	}

}
