package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 696804439326990441L;
	private String productId;
	private String name;
	private String description;
	private int bundles;
	private int bundleSize;
	private int dataLimit;
	@JsonIgnore
	private String username;
	@JsonIgnore
	private String password;
	@JsonIgnore
	private String key;
	private boolean isActive;
	private boolean useTelkomCredentials;
	@JsonIgnore
	private Set<Device> devices = new HashSet<Device>(0);
	@JsonIgnore
	private Set<Productpriceplan> productpriceplans = new HashSet<Productpriceplan>(0);
	@JsonIgnore
	private Set<Productsupport> productsupports = new HashSet<Productsupport>(0);
	@JsonIgnore
	private Set<Faq> faqs = new HashSet<Faq>(0);
	@JsonIgnore
	private Set<Productcoverage> productcoverages = new HashSet<Productcoverage>(0);
	@JsonIgnore
	private Set<Zone> zones = new HashSet<Zone>(0);

	public Product() {
	}

	public Product(String productId, String name, String description, String username, String password, String key, boolean isActive, int bundles, int bundleSize, int dataLimit, boolean useTelkomCredentials) {
		this.productId = productId;
		this.name = name;
		this.description = description;
		this.username = username;
		this.password = password;
		this.key = key;
		this.isActive = isActive;
		this.useTelkomCredentials = useTelkomCredentials;
		this.bundles = bundles;
		this.bundleSize = bundleSize;
		this.dataLimit = dataLimit;
	}

	public Product(String productId, String name, String description, String username, String password, String key, boolean isActive, int bundles, int bundleSize, int dataLimit,
			boolean useTelkomCredentials, Set<Device> devices, Set<Productpriceplan> productpriceplans, Set<Productsupport> productsupports,
			Set<Faq> faqs, Set<Productcoverage> productcoverages, Set<Zone> zones) {
		this.productId = productId;
		this.name = name;
		this.description = description;
		this.username = username;
		this.password = password;
		this.key = key;
		this.isActive = isActive;
		this.bundles = bundles;
		this.bundleSize = bundleSize;
		this.dataLimit = dataLimit;
		this.useTelkomCredentials = useTelkomCredentials;
		this.devices = devices;
		this.productpriceplans = productpriceplans;
		this.productsupports = productsupports;
		this.faqs = faqs;
		this.productcoverages = productcoverages;
		this.zones = zones;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}
	
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}
	
	public int getBundles() {
		return this.bundles;
	}

	public void setBundles(int bundles) {
		this.bundles = bundles;
	}
	
	public int getBundleSize() {
		return this.bundleSize;
	}

	public void setBundleSize(int bundleSize) {
		this.bundleSize = bundleSize;
	}
	
	public int getDataLimit() {
		return this.dataLimit;
	}

	public void setDataLimit(int dataLimit) {
		this.dataLimit = dataLimit;
	}
	
	public boolean isUseTelkomCredentials() {
		return useTelkomCredentials;
	}

	public void setUseTelkomCredentials(boolean useTelkomCredentials) {
		this.useTelkomCredentials = useTelkomCredentials;
	}

	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}

	public Set<Productpriceplan> getProductpriceplans() {
		return this.productpriceplans;
	}

	public void setProductpriceplans(Set<Productpriceplan> productpriceplans) {
		this.productpriceplans = productpriceplans;
	}

	public Set<Productsupport> getProductsupports() {
		return this.productsupports;
	}

	public void setProductsupports(Set<Productsupport> productsupports) {
		this.productsupports = productsupports;
	}

	public Set<Faq> getFaqs() {
		return this.faqs;
	}

	public void setFaqs(Set<Faq> faqs) {
		this.faqs = faqs;
	}

	public Set<Productcoverage> getProductcoverages() {
		return this.productcoverages;
	}

	public void setProductcoverages(Set<Productcoverage> productcoverages) {
		this.productcoverages = productcoverages;
	}
	
	public Set<Zone> getZones() {
		return this.zones;
	}

	public void setZones(Set<Zone> zones) {
		this.zones = zones;
	}
}
