package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Productpriceplan generated by hbm2java
 */
public class Productpriceplan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 936491884301697755L;
	private String productPricePlanId;
	private Product product;
	private String heading;
	private String details;

	public Productpriceplan() {
	}

	public Productpriceplan(String productPricePlanId, Product product, String heading, String details) {
		this.productPricePlanId = productPricePlanId;
		this.product = product;
		this.heading = heading;
		this.details = details;
	}

	public String getProductPricePlanId() {
		return this.productPricePlanId;
	}

	public void setProductPricePlanId(String productPricePlanId) {
		this.productPricePlanId = productPricePlanId;
	}

	@JsonIgnore
	public Product getProduct() {
		return this.product;
	}

	@JsonProperty
	public void setProduct(Product product) {
		this.product = product;
	}

	public String getHeading() {
		return this.heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

}
