package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final


/**
 * Subscriber generated by hbm2java
 */
public class Subscriber implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1642154124046514942L;
	private String subscriberId;
	private Company company;
	private Device device;
	private String name;
	private String email;

	public Subscriber() {
	}

	public Subscriber(String subscriberId, Device device, String name) {
		this.subscriberId = subscriberId;
		this.device = device;
		this.name = name;
	}

	public Subscriber(String subscriberId, Company company, Device device, String name, String email) {
		this.subscriberId = subscriberId;
		this.company = company;
		this.device = device;
		this.name = name;
		this.email = email;
	}

	public String getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(String subscriberId) {
		this.subscriberId = subscriberId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
