package com.execmobile.data;
// Generated Jan 31, 2016 10:08:23 PM by Hibernate Tools 4.3.1.Final


/**
 * Usage generated by hbm2java
 */
public class Usage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7016540888696343112L;
	private String usageId;
	private Country country;
	private String recordDate;
	private String data;
	private Integer bundles;
	private String zone;
	private String base;
	private String ext;
	private String total;
	private Device device;

	public Usage() {
	}

	public Usage(String usageId, String recordDate, String data, String zone, Device device) {
		this.usageId = usageId;
		this.recordDate = recordDate;
		this.data = data;
		this.zone = zone;
		this.device = device;
	}

	public Usage(String usageId, Country country, String recordDate, String data, Integer bundles,
			String zone, String base, String ext, String total, Device device) {
		this.usageId = usageId;
		this.country = country;
		this.recordDate = recordDate;
		this.data = data;
		this.bundles = bundles;
		this.zone = zone;
		this.base = base;
		this.ext = ext;
		this.total = total;
		this.device = device;
	}
	
	public String getUsageId() {
		return this.usageId;
	}

	public void setUsageId(String usageId) {
		this.usageId = usageId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(String recordDate) {
		this.recordDate = recordDate;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public Integer getBundles() {
		return this.bundles;
	}

	public void setBundles(Integer bundles) {
		this.bundles = bundles;
	}

	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	public String getBase() {
		return this.base;
	}

	public void setBase(String base) {
		this.base = base;
	}

	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	public String getTotal() {
		return this.total;
	}

	public void setTotal(String total) {
		this.total = total;
	}
	
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

}
