//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.02 at 01:20:15 PM CAT 
//


package com.execmobile.models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.execmobile.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.execmobile.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WebbingCredentials }
     * 
     */
    public WebbingCredentials createWebbingCredentials() {
        return new WebbingCredentials();
    }

    /**
     * Create an instance of {@link WebbingCredentials.Default }
     * 
     */
    public WebbingCredentials.Default createWebbingCredentialsDefault() {
        return new WebbingCredentials.Default();
    }

    /**
     * Create an instance of {@link WebbingCredentials.Telkom }
     * 
     */
    public WebbingCredentials.Telkom createWebbingCredentialsTelkom() {
        return new WebbingCredentials.Telkom();
    }

}
